### PR TITLE
Porting index refresh from previous release

### LINKED ISSUE #48: Bring back the index refresh support
One of the features I miss from the old unoconv, is the automatic update of indexes and ToC before the conversion.
I created a branch, where I re-added the `for cicle` needed to refresh the indexes. And it just works !

I hope you can bring back this feature in a future release!

### PR DESCRIPTION
**Pull request by AlePini**
Fixes #48

### CODE REVIEW

**Comment by regebro** [comment]
Looks good, I will do some testing of this next week.

**Comment by regebro** [comment]
Oh, and if can you add yourself to the contributors list in CONTRIBUTORS.rst, and add a change note in CHANGES.rst that would be great!

**Comment by AlePini** [comment]
Changed the name of this merge requeste, since "backporting" means the exact opposite of what I meant XD

Should be good now 👍🏻

**Comment by vijayarun** [comment]
Any update

**Comment by vijayarun** [comment]
@regebro If there is no issue with the merge request, then can we merge it?

**Comment by regebro** [comment]
No, the only issue is time for me to test it.

**Pull request merged**
