### PR TITLE
example rpc server implementation, addressing #29

### PR DESCRIPTION
**Pull request by hottwaj**
This is a v quick example of changes needed to make converter.py optionally provide an rpc server so that Converter.convert can be called from remote processes in virtualenvs

A separate rpc client module is needed, and that would be the module that users need to install into their virtualenv

### CODE REVIEW

**Comment by regebro** [comment]
I'll talk with the rest of the people involved if we want to maintain this or not.

**Comment by regebro** [comment]
The conclusion was basically that this is a good idea, and we would like to see a version where the client exclusively talks to the backend this way, so the client doesn't need to import uno at all, and that the server does that instead.

**Comment by hottwaj** [comment]
Thanks & great - sounds like a plan!  What would you like to see next (in terms of changes to the code in this PR) to progress?

**Comment by regebro** [comment]
Well, the `unoserver` should start the server, and always start it, in a separate process or thread. I guess async could be used? We also will have to make a specification/documentation of the protocol, and tests. We also need to account for other commands except converting, a compare command has been proposed in another PR, and that's an interesting idea. 

After that a client that uses that protocol could be made. 

I think the easiest for that is to let the UnoConverter reside in the converter.py class and make a new client in a client module.

**Comment by regebro** [comment]
2.0a1 is out now

**Pull request closed without merging**
